apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-xs0d
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-xs0d
    app.kubernetes.io/part-of: my-app-6
  name: devfile-sample-python-basic-xs0d
spec:
  rules:
  - host: devfile-sample-python-basic-xs0d-pshivpuj-tenant.$121.ip.io
    http:
      paths:
      - backend:
          service:
            name: devfile-sample-python-basic-xs0d
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
